class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:create]
  # redirect from the signin page if a user is already signed in
  before_action :redirect_if_signed_in, only: [:create]

  def create
    user = User.where(:uid => auth_hash.uid).first_or_create!(name: auth_hash.info.name, email: auth_hash.info.email)
    # render :text => auth_hash.to_yaml
    sign_in user
    redirect_back_or user
  end

  def destroy
    sign_out
    redirect_to root_url
  end

  def oauth_failure
    sign_out
    flash[:error] = "You must log into Venmo to continue"
    redirect_to root_url
  end

  private

    # Get the authorization request object, generated by Omniauth
    def auth_hash
      request.env['omniauth.auth']
    end
end